### ISSUE TITLE
Versions of numpy starting in 2.X will fail due to bool8 data-type being removed

### ISSUE THREAD

**Issue by ssssarah** [BlueBrain/voxcell#35]
https://numpy.org/devdocs/release/2.0.0-notes.html 

#Support for seven data type string aliases has been removed from np.dtype: int0, uint0, void0, object0, str0, bytes0 and bool8.
([gh-24807](https://github.com/numpy/numpy/pull/24807)) 

```
Traceback (most recent call last):
  File "./src/my_script.py", line 9, in <module>
    from voxcell import RegionMap, VoxelData
  File "./venv2/lib/python3.11/site-packages/voxcell/__init__.py", line 6, in <module>
    from voxcell.voxel_data import (
  File "./venv2/lib/python3.11/site-packages/voxcell/voxel_data.py", line 4, in <module>
    import nrrd
  File "./venv2/lib/python3.11/site-packages/nrrd/__init__.py", line 2, in <module>
    from nrrd.formatters import *
  File "./venv2/lib/python3.11/site-packages/nrrd/formatters.py", line 3, in <module>
    import nptyping as npt
  File "./venv2/lib/python3.11/site-packages/nptyping/__init__.py", line 30, in <module>
    from nptyping.ndarray import NDArray
  File "./venv2/lib/python3.11/site-packages/nptyping/ndarray.py", line 32, in <module>
    from nptyping.shape_expression import (
  File "./venv2/lib/python3.11/site-packages/nptyping/shape_expression.py", line 35, in <module>
    from nptyping.typing_ import Literal
  File "./venv2/lib/python3.11/site-packages/nptyping/typing_.py", line 66, in <module>
    Bool8: TypeAlias = np.bool8
                       ^^^^^^^^
  File "./venv2/lib/python3.11/site-packages/numpy/__init__.py", line 410, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool8'. Did you mean: 'bool'?
```

Looks like this is not directly a voxcell issue but maybe capping the numpy version can help prevent this problem?

**Comment by mgeplf** [comment]
Capping the numpy would be dangerous, since it impacts the resolver, and it's not really a hard dependency.

@eleftherioszisis successfully got pynrrd to drop it, so once that's released, we should be in the clear: https://github.com/mhe/pynrrd/pull/154

**Comment by ssssarah** [comment]
Cool, indeed it's much better. Thanks!

**Comment by mgeplf** [comment]
We'll have to see when a release is made, perhaps I will ping the maintainer.

**Comment by mgeplf** [comment]
A release has been made, so nptyping isn't used, and this error will go away.
However, their API has changed, so we have another thing to fix: https://github.com/BlueBrain/voxcell/issues/37
